title: "Youjin Lee"
description: "Computer Graphics Engineer & Painter"
about: "Computer Graphics Engineer & Painter"
location: "Seoul, South Korea"
email: yjin1588@gmail.com
baseurl: "/"

url: "https://yjin1588.github.io" # replace by your site's url
twitter_username: yjin1588
github_username:  yjin1588
author: "Youjin Lee"

# google analytics tracking code, please change the value
g_analytics: ""

# add your disqus to enable comments
disqus_shortname:

# add your disqus to enable comments
disqus_shortname:

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
publications_btn: "Publications"
drawings_btn: "Drawings"
animations_btn: "Animations"
imprint_btn: "Imprint"
name_badge: "an article by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    tab_width: 4

# third party gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# exclude files
exclude:
  - LICENSE
  - README.md
